
services:

  backend:
    image: comis/knote-java:dev
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPINRG_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: dev
      SPRING_DATA_MONGODB_USERNAME: mongoadmin
      SPRING_DATA_MONGODB_PASSWORD: password123
    networks:
      - spring-mongo

  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=dev
    volumes:
      - mongo_data:/data/db
    networks:
      - spring-mongo


networks:
  spring-mongo:

volumes:
  mongo_data: